
spring.profiles.active: ${SPRING_PROFILE_ACTIVE}
server:
  port: 8090
---
spring:
  h2:
    console:
      enabled: true
      path: "/h2-console"
  jpa:
    show_sql: true
    database: H2
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: true
  config:
    activate:
      on-profile: develop
---
spring:
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
  config:
    activate:
      on-profile: test
---
spring:
  jpa:
    show_sql: false
    database: H2
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: true
  config:
    activate:
      on-profile: integration-test
---
spring:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  config:
    activate:
      on-profile: release